name: create-release
run-name: Create release '${{ inputs.release_version_number }}'
# What it does:
# - Call release-prepare_no_maven workflow
# - Call release-publish-draft-and-pr
on:
  workflow_dispatch:
    inputs:
      notes:
        description: "Release notes"
        required: false
        type: string
        default: ''
      release_version_number:
        description: "Provide release version number"
        required: true
        type: string

jobs:

  release_prepare_no_maven: # prepare for a release in scm, creates the tag and release branch with the proper release versions
    name: Call release prepare
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-prepare-no-maven.yml@master
    with:
      release_version_number: ${{ inputs.release_version_number }}
    secrets:
      GIT_COMMIT_USERNAME_BOT: ${{ secrets.GIT_COMMIT_USERNAME_BOT }}
      GIT_COMMIT_AUTHOR_EMAIL_BOT: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}
      release_github_token: ${{ secrets.RELEASE_PAT }}


  release_draft:
    name: Call publish
    needs: [ release_prepare_no_maven ]
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-publish.yml@master
    with:
      release_version_number: ${{ inputs.release_version_number }}
      release_tag_ref: ${{ needs.release_prepare_no_maven.outputs.release_tag_ref }}
      release_notes: ${{ inputs.notes }}
    secrets:
      release_github_token: ${{ secrets.RELEASE_PAT }}
